// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: proto/data.proto

package protoconnect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	proto "github.com/sword-jin/caddy-frp-grpc-streaming/proto"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// ServiceName is the fully-qualified name of the Service service.
	ServiceName = "protobuf.Service"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// ServiceUnaryProcedure is the fully-qualified name of the Service's Unary RPC.
	ServiceUnaryProcedure = "/protobuf.Service/Unary"
	// ServiceStreamProcedure is the fully-qualified name of the Service's Stream RPC.
	ServiceStreamProcedure = "/protobuf.Service/Stream"
)

// These variables are the protoreflect.Descriptor objects for the RPCs defined in this package.
var (
	serviceServiceDescriptor      = proto.File_proto_data_proto.Services().ByName("Service")
	serviceUnaryMethodDescriptor  = serviceServiceDescriptor.Methods().ByName("Unary")
	serviceStreamMethodDescriptor = serviceServiceDescriptor.Methods().ByName("Stream")
)

// ServiceClient is a client for the protobuf.Service service.
type ServiceClient interface {
	Unary(context.Context, *connect.Request[proto.Request]) (*connect.Response[proto.Response], error)
	Stream(context.Context, *connect.Request[proto.Request]) (*connect.ServerStreamForClient[proto.Response], error)
}

// NewServiceClient constructs a client for the protobuf.Service service. By default, it uses the
// Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and sends
// uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or
// connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) ServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	return &serviceClient{
		unary: connect.NewClient[proto.Request, proto.Response](
			httpClient,
			baseURL+ServiceUnaryProcedure,
			connect.WithSchema(serviceUnaryMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		stream: connect.NewClient[proto.Request, proto.Response](
			httpClient,
			baseURL+ServiceStreamProcedure,
			connect.WithSchema(serviceStreamMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
	}
}

// serviceClient implements ServiceClient.
type serviceClient struct {
	unary  *connect.Client[proto.Request, proto.Response]
	stream *connect.Client[proto.Request, proto.Response]
}

// Unary calls protobuf.Service.Unary.
func (c *serviceClient) Unary(ctx context.Context, req *connect.Request[proto.Request]) (*connect.Response[proto.Response], error) {
	return c.unary.CallUnary(ctx, req)
}

// Stream calls protobuf.Service.Stream.
func (c *serviceClient) Stream(ctx context.Context, req *connect.Request[proto.Request]) (*connect.ServerStreamForClient[proto.Response], error) {
	return c.stream.CallServerStream(ctx, req)
}

// ServiceHandler is an implementation of the protobuf.Service service.
type ServiceHandler interface {
	Unary(context.Context, *connect.Request[proto.Request]) (*connect.Response[proto.Response], error)
	Stream(context.Context, *connect.Request[proto.Request], *connect.ServerStream[proto.Response]) error
}

// NewServiceHandler builds an HTTP handler from the service implementation. It returns the path on
// which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewServiceHandler(svc ServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	serviceUnaryHandler := connect.NewUnaryHandler(
		ServiceUnaryProcedure,
		svc.Unary,
		connect.WithSchema(serviceUnaryMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	serviceStreamHandler := connect.NewServerStreamHandler(
		ServiceStreamProcedure,
		svc.Stream,
		connect.WithSchema(serviceStreamMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	return "/protobuf.Service/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case ServiceUnaryProcedure:
			serviceUnaryHandler.ServeHTTP(w, r)
		case ServiceStreamProcedure:
			serviceStreamHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedServiceHandler struct{}

func (UnimplementedServiceHandler) Unary(context.Context, *connect.Request[proto.Request]) (*connect.Response[proto.Response], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("protobuf.Service.Unary is not implemented"))
}

func (UnimplementedServiceHandler) Stream(context.Context, *connect.Request[proto.Request], *connect.ServerStream[proto.Response]) error {
	return connect.NewError(connect.CodeUnimplemented, errors.New("protobuf.Service.Stream is not implemented"))
}
